### ISSUE TITLE
malformed input around byte 25

### ISSUE THREAD

**Issue by zhys513** [iNPUTmice/ceb2txt#1]
java.io.UTFDataFormatException: malformed input around byte 25
	at java.io.DataInputStream.readUTF(DataInputStream.java:656)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at im.conversations.ceb2txt.BackupFileHeader.read(BackupFileHeader.java:53)
	at im.conversations.ceb2txt.Main.main(Main.java:62)
C:\Users\Administrator\Desktop\111\1.ceb does not seem to be a valid backup file

**Comment by zhys513** [comment]
Thank you. The version of ceb is CEB 3.0

**Comment by licaon-kter** [comment]
@zhys513 That's not what I've asked...

**Comment by zhys513** [comment]
inputStream.readInt() = 1181709678   is this?

**Comment by licaon-kter** [comment]
Not sure you are in the right place.

Where did you get the CEB file from?

**Comment by iNPUTmice** [comment]
I think the error message already explains this. Your backup file is probably corrupt.
