### ISSUE TITLE
JCE cannot authenticate the provider Conscrypt

### ISSUE THREAD

**Issue by mu88** [iNPUTmice/ceb2txt#10]
# Versions
Java Runtime Environment 1.8.0_271-b09 (x64)
Conversations 2.9.0+fcr (via Google Play)
Android 10

# Problem
I've created a backup with Conversations on my smartphone. Now I'm trying to export the chat messages into plain text files using your nice helper tool. Unfortunately, it fails with the following error after entering the password:
```
java -jar im.conversations.ceb2txt-0.1.jar myuser@mydomain.com.ceb
Enter password for myuser@mydomain.com:
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider Conscrypt
        at javax.crypto.Cipher.getInstance(Cipher.java:660)
        at im.conversations.ceb2txt.Main.main(Main.java:68)
Caused by: java.util.jar.JarException: file:/C:/temp/im.conversations.ceb2txt-0.1.jar has unsigned entries - im/conversations/ceb2txt/entities/Message$FileParams.class
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:510)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:371)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:297)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
        at javax.crypto.Cipher.getInstance(Cipher.java:656)
        ... 1 more
```
I've doublechecked the password and created a new backup file - the problem persists.

Do you have any ideas about that? Thank you!

**Comment by surentharp** [comment]
@mu88 I can successfully convert it by using Java 11. I also met up with this error when I used Java 8.
