### ISSUE TITLE
Cannot decrypt CEB file created by version 2.12.1

### ISSUE THREAD

**Issue by multimob** [iNPUTmice/ceb2txt#15]
It used to work fine with backups until 2.10.10.

This is the output when attempting to open a CEB file created by 2.12.1+free (F-Droid).

`Exception in thread "main" org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (table accounts has no column named pinned_mechanism)
        at org.sql2o.Query.buildPreparedStatement(Query.java:439)
        at org.sql2o.Query.buildPreparedStatement(Query.java:421)
        at org.sql2o.Query.executeUpdate(Query.java:652)
        at im.conversations.ceb2txt.Main.main(Main.java:140)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table accounts has no column named pinned_mechanism)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
        at org.sqlite.core.DB.prepare(DB.java:257)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
        at org.sql2o.Query.buildPreparedStatement(Query.java:434)
        ... 3 more
`

The reference to pinned_mechanism is found in parts of code that changed in recent versions, e.g. this line in src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java:
`Account.PINNED_MECHANISM + " TEXT,"`

**Comment by aslmx** [comment]
Same here :( 
Can't export my messages with a recent backup.

**Comment by licaon-kter** [comment]
@aslmx the issue is about IMPORTING or DECRYPTING or RESTORING

You can't EXPORT? That sounds... different

**Comment by multimob** [comment]
Conversations exports backups into CEB files.
Importing a CEB file to another device running Conversations (aka restoring) = works fine.
Decrypting the CEB file with ceb2txt (to get TXT files) = broken.

**Comment by aslmx** [comment]
> @aslmx the issue is about IMPORTING or DECRYPTING or RESTORING
> You can't EXPORT? That sounds... different

Sorry, I meant to write "i cant use ceb2txt to export the message from *.ceb to *.txt"

@iNPUTmice  thanks for fixing this. I was surprised how easy it was to build this and now it works for me! Great! Thanks!
