### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by CroneG** [iNPUTmice/ceb2txt#2]
Exception in thread "main" java.security.InvalidAlgorithmParameterException: Unsupported parameter: javax.crypto.spec.IvParameterSpec@7bb11784
        at java.base/com.sun.crypto.provider.CipherCore.init(CipherCore.java:518)
        at java.base/com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:346)
        at java.base/javax.crypto.Cipher.implInit(Cipher.java:874)
        at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:932)
        at java.base/javax.crypto.Cipher.init(Cipher.java:1447)
        at java.base/javax.crypto.Cipher.init(Cipher.java:1378)
        at im.conversations.ceb2txt.Main.main(Main.java:79)

**Comment by iNPUTmice** [comment]
Your backup file is probably corrupt. Fixed in 6f9994201abd3899be7d46eb39d2527f8a36717d

**Comment by CroneG** [comment]
Nah. It imports in Conversations and Conversations forks properly. Something wrong with software :/
