### ISSUE TITLE
NullPointerException in Message.getCounterpart

### ISSUE THREAD

**Issue by tpreclik** [iNPUTmice/ceb2txt#20]
I get multiple null pointer exceptions when decrypting my backup:

```
Exception in thread "main" java.lang.NullPointerException
	at org.jxmpp.jid.impl.JidCreate.from(JidCreate.java:177)
	at org.jxmpp.jid.impl.JidCreate.fromOrNull(JidCreate.java:220)
	at im.conversations.ceb2txt.entities.Message.getCounterpart(Message.java:124)
	at im.conversations.ceb2txt.Main.main(Main.java:199)
```

Sounds like #14 is related. The corresponding `counterpart` string in Message leading to the exceptions were in my case either null or `conversations@conference.siacs.eu/`. These were the corresponding messages generated in the output when catching the exception and setting `nick` to `NULLPOINTEREXCEPTION`:

```
./group/hidden@conference.jabber.de/2017-06-26.txt:23:23 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/hidden@conference.jabber.de/2017-06-26.txt:23:24 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/hidden@conference.jabber.de/2017-06-22.txt:08:15 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/hidden@conference.jabber.de/2017-06-18.txt:21:05 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/conversations@conference.siacs.eu/2023-05-05.txt:03:26 NULLPOINTEREXCEPTION <- dam spammers
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:31 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:31 NULLPOINTEREXCEPTION <- Www.google.com
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠                                          
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
```

A proper fix should be proposed by a more knowledgeable person.

**Comment by shamefulCake1** [comment]
I have the same error:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.jxmpp.jid.Jid.getResourceOrEmpty()" because the return value of "im.conversations.ceb2txt.entities.Message.getCounterpart()" is null
	at im.conversations.ceb2txt.Main.main(Main.java:199)
```

**Comment by licaon-kter** [comment]
@shamefulCake1 more details? OS used? Java version used? Conversations version used for backup?

**Comment by shamefulCake1** [comment]
@licaon-kter 

It is exactly the same place as @tpreclik has it.

```
openjdk version "17.0.12" 2024-07-16 LTS
OpenJDK Runtime Environment Zulu17.52+17-CA (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.52+17-CA (build 17.0.12+7-LTS, mixed mode, sharing)
```

Conversations 2.16.7+free m119

I also patched the source, like @tpreclik did:

```
diff --git a/src/main/java/im/conversations/ceb2txt/Main.java b/src/main/java/im/conversations/ceb2txt/Main.java
index 15b06b9..ed73821 100644
--- a/src/main/java/im/conversations/ceb2txt/Main.java
+++ b/src/main/java/im/conversations/ceb2txt/Main.java
@@ -195,8 +195,13 @@ public class Main {
                     conversationFile.getParentFile().mkdirs();
                     writer = new PrintWriter(conversationFile);
                 }
+
                 final String nick =
-                        group ? message.getCounterpart().getResourceOrEmpty().toString() : "";
+                        group
+                                ? ((message.getCounterpart() != null)
+                                        ? message.getCounterpart().getResourceOrEmpty().toString()
+                                        : "_nocounterpart_")
+                                : "";
                 writer.println(
                         TIME_FORMAT.format(date)
                                 + " "
```

And in my case it produces one error, but in the same place:

```
/group/conversations@conference.siacs.eu/2023-05-05.txt:09:26 _nocounterpart_ <- dam spammers
```

The `counterpart` argument to `getCounterpart()` leading to this is just `conversations@conference.siacs.eu/` without a resource. Or maybe the resource is a space, non-breakable space, or a Mongolian vowel separator.
