### ISSUE TITLE
Broken since Conversations 2.17 - columns to update

### ISSUE THREAD

**Issue by multimob** [iNPUTmice/ceb2txt#23]
CEB files created with the most recent version of Conversations (2.17.2) will fail.

It looks like this commit modified the tables: https://codeberg.org/iNPUTmice/Conversations/commit/41057ffc6597c70aeaa88667b09e31278c4c37b0

```
Exception in thread "main" org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (table messages has no column named reactions)
        at org.sql2o.Query.buildPreparedStatement(Query.java:439)
        at org.sql2o.Query.buildPreparedStatement(Query.java:421)
        at org.sql2o.Query.executeUpdate(Query.java:652)
        at im.conversations.ceb2txt.Main.importRow(Main.java:312)
        at im.conversations.ceb2txt.Main.importV2Backup(Main.java:262)
        at im.conversations.ceb2txt.Main.main(Main.java:147)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table messages has no column named reactions)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.throwex(DB.java:1150)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
        at org.sqlite.core.DB.prepare(DB.java:264)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:211)
        at org.sql2o.Query.buildPreparedStatement(Query.java:434)
        ... 5 more

```

**Comment by licaon-kter** [comment]
Fixed in https://github.com/iNPUTmice/ceb2txt/commit/1c0f45145ae47afe4dd850457672690b003c67e3 right?

**Comment by multimob** [comment]
Indeed.
