### ISSUE TITLE
Backup is importable on Android, but not in this app

### ISSUE THREAD

**Issue by CroneG** [iNPUTmice/ceb2txt#3]

**Comment by licaon-kter** [comment]
@CroneG  add mare info, errors, etc?

**Comment by CroneG** [comment]
Exception in thread "main" java.security.InvalidAlgorithmParameterException: Unsupported parameter: javax.crypto.spec.IvParameterSpec@7bb11784
at java.base/com.sun.crypto.provider.CipherCore.init(CipherCore.java:518)
at java.base/com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:346)
at java.base/javax.crypto.Cipher.implInit(Cipher.java:874)
at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:932)
at java.base/javax.crypto.Cipher.init(Cipher.java:1447)
at java.base/javax.crypto.Cipher.init(Cipher.java:1378)
at im.conversations.ceb2txt.Main.main(Main.java:79)

Despite that error BackupFileHeader.toString() works properly. File is not corrupted.

**Comment by licaon-kter** [comment]
/close as duplicate #2

`git pull ; mvn package`

**Comment by CroneG** [comment]
Still doesn't work. Why not just copy code from Conversations.im? It's little bit different than in this project

**Comment by CroneG** [comment]
I don't know Java, so what I did is:
1) Import backup into Conversations.im
2) Remove encryption during backup (Changing Conversations.im code)
3) Backup. (Backup is unencrypted)
4) Now I will try to modify current app to pass unencrypted backup to make DB file.

**Comment by CroneG** [comment]
Unfortunately, I can't share solution because I don't know Java. I'm trying by trials and errors.
